use clippy_utils::res::MaybeDef;
use rustc_hir::{Item, ItemKind};
use rustc_lint::{LateContext, LateLintPass};
use rustc_middle::ty::{Ty, TyKind};
use rustc_session::declare_lint_pass;
use rustc_span::sym;

use crate::def_path::def_path_eq;
use crate::diagnostics::span_lint_and_then;

declare_waterui_lint! {
    /// ### What it does
    ///
    /// Flags a bare `RefCell<_>`/`Cell<_>` field on a `#[derive(Clone)]`
    /// struct when a sibling field already shares state through
    /// `Rc<RefCell<_>>` or `Rc<Cell<_>>`.
    ///
    /// ### Why is this bad?
    ///
    /// Derived `Clone` copies every field; a shared `Rc` cell survives the
    /// copy as the same state, but a bare cell is duplicated — each clone
    /// gets its own detached copy. With a `Rc<RefCell<_>>` sibling in the
    /// same struct, the bare cell is almost always a missed sharing intent:
    /// clones silently diverge — a cloned `AppState` whose undo stack does
    /// nothing.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// #[derive(Clone)]
    /// struct AppState {
    ///     tabs: Rc<RefCell<Vec<ClosedTab>>>,
    ///     undo: RefCell<Vec<ClosedTab>>, // forks on every clone
    /// }
    /// ```
    ///
    /// Share the cell the way its sibling already does:
    ///
    /// ```rust,ignore
    /// #[derive(Clone)]
    /// struct AppState {
    ///     tabs: Rc<RefCell<Vec<ClosedTab>>>,
    ///     undo: Rc<RefCell<Vec<ClosedTab>>>,
    /// }
    /// ```
    ///
    /// A hand-written `impl Clone` stays silent: what it does with each
    /// field is the author's choice, not the mechanical field-copy this
    /// lint targets.
    pub CLONE_REFCELL_FIELD,
    suspicious,
    "bare `RefCell`/`Cell` field on a `Clone` struct forks the state on every clone"
}

declare_lint_pass!(CloneRefcellField => [CLONE_REFCELL_FIELD]);

/// The single-threaded cell types a derived `Clone` copies instead of
/// sharing.
const CELL_TYPES: &[&[&str]] = &[&["core", "cell", "Cell"], &["core", "cell", "RefCell"]];

/// Whether `ty`, as written, is a bare `Cell`/`RefCell` — a `&RefCell`
/// field borrows shared state and clones share it correctly, so it must
/// not match.
fn is_cell_ty(cx: &LateContext<'_>, ty: Ty<'_>) -> bool {
    ty.ty_adt_def().is_some_and(|adt| {
        CELL_TYPES
            .iter()
            .any(|path| def_path_eq(cx, adt.did(), path))
    })
}

/// Whether `ty`, as written, is `Rc` over one of `CELL_TYPES` — the
/// sibling shape that shows the struct already shares cell state.
fn is_rc_cell_ty(cx: &LateContext<'_>, ty: Ty<'_>) -> bool {
    let TyKind::Adt(adt, args) = *ty.kind() else {
        return false;
    };
    adt.is_diag_item(cx, sym::Rc) && is_cell_ty(cx, args.type_at(0))
}

/// Whether `self_ty`'s `Clone` impl was generated by `#[derive(Clone)]`.
fn derives_clone<'tcx>(cx: &LateContext<'tcx>, self_ty: Ty<'tcx>) -> bool {
    let Some(clone) = cx.tcx.lang_items().clone_trait() else {
        return false;
    };
    cx.tcx
        .non_blanket_impls_for_ty(clone, self_ty)
        .any(|impl_did| cx.tcx.is_automatically_derived(impl_did))
}

impl<'tcx> LateLintPass<'tcx> for CloneRefcellField {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        if item.span.from_expansion() {
            return;
        }
        let ItemKind::Struct(..) = &item.kind else {
            return;
        };
        let self_ty = cx
            .tcx
            .type_of(item.owner_id.to_def_id())
            .instantiate_identity()
            .skip_norm_wip();
        let TyKind::Adt(adt, args) = *self_ty.kind() else {
            return;
        };
        if !derives_clone(cx, self_ty)
            || !adt
                .all_fields()
                .any(|field| is_rc_cell_ty(cx, field.ty(cx.tcx, args).skip_norm_wip()))
        {
            return;
        }
        for field in adt.all_fields() {
            let ty = field.ty(cx.tcx, args).skip_norm_wip();
            if !is_cell_ty(cx, ty) {
                continue;
            }
            span_lint_and_then(
                cx,
                CLONE_REFCELL_FIELD,
                cx.tcx.def_span(field.did),
                format!(
                    "`{}` forks this state on every `Clone` — each copy gets its own cell",
                    field.name
                ),
                |diag| {
                    diag.help(format!("share it like the `Rc` sibling: `Rc<{}>`", ty));
                },
            );
        }
    }
}
